stages:
  - build
  - test
  - deploy

before_script:
  - echo "Setting up environment"
  - apt update -y && apt install -y curl cargo libssl-dev pkg-config
  - curl -fsSL https://get.docker.com -o get-docker.sh
  - sh ./get-docker.sh

build-job:
  stage: build
  script:
    - echo "Compiling services and publishing to local registry..."
    - docker compose build

unit-test-job:
  stage: test
  script:
    - echo "Running unit tests..."
    - echo "Running service1 unit tests..."
    - cd ./service1 && cargo test && cd ..
    - echo "Running service2 unit tests..."
    - cd ./service2 && ./gradlew test && cd ..
    - echo "Running monitor unit tests..."
    - cd ./monitor && ./gradlew test && cd ..

integration-test-job:
  stage: test
  script:
    - echo "Running integration tests..."
    - docker compose -p testing-env up -d
    - echo "Testing..."
    - docker compose -p testing-env down

deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "Deploying application..."
    - docker compose up -d
