version: '3'
services:
  service1:
    build: ./service1
    depends_on:
      broker:
        condition: service_healthy
    environment:
      - SERVER_URL=service2:8000
      - RABBIT_MQ_HOST=broker
    networks:
      - internal

  service2:
    build: ./service2
    depends_on:
      broker:
        condition: service_healthy
    environment:
      - RABBIT_MQ_HOST=broker
    networks:
      - internal

  broker:
    build: ./broker
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 30s
      retries: 10
    networks:
      - internal

  monitor:
    build: ./monitor
    depends_on:
      broker:
        condition: service_healthy
    environment:
      - SPRING_RABBITMQ_HOST=broker
    volumes:
      - logs:/logs
    networks:
      - internal

  gateway:
    build: ./gateway
    ports:
      - "${GATEWAY_PORT:-8083}:80"
    networks:
      - internal
      - default

  prometheus:
    build: ./prometheus
    networks:
      - internal

  grafana:
    build: ./grafana
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    depends_on:
      - prometheus
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - internal
      - default

networks:
  default:
  internal:
    internal: true

volumes:
  logs:
  grafana-data: