version: '3'
services:
  service1:
    build: ./service1
    depends_on:
      broker:
        condition: service_healthy
    environment:
      - SERVER_URL=service2:8000
      - RABBIT_MQ_HOST=broker
    networks:
      - internal

  service2:
    build: ./service2
    depends_on:
      broker:
        condition: service_healthy
    environment:
      - RABBIT_MQ_HOST=broker
    networks:
      - internal

  broker:
    image: rabbitmq:3.12.6-management-alpine
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 30s
      retries: 10
    networks:
      - internal
    volumes:
      - ./broker/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./broker/definitions.json:/etc/rabbitmq/definitions.json:ro

  monitor:
    build: ./monitor
    depends_on:
      broker:
        condition: service_healthy
    ports:
      - "${MONITOR_PORT:-8087}:8080"
    environment:
      - SPRING_RABBITMQ_HOST=broker
    networks:
      - internal
      - default

networks:
  default:
  internal:
    name: rnvako_internal
    internal: true