version: '3'
services:
  service1:
    build: ./service1
    depends_on:
      broker:
        condition: service_healthy
    environment:
      - SERVER_URL=service2:8000
      - RABBIT_MQ_HOST=broker
    networks:
      - internal

  service2:
    build: ./service2
    depends_on:
      broker:
        condition: service_healthy
    environment:
      - RABBIT_MQ_HOST=broker
    networks:
      - internal

  broker:
    build: ./broker
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 30s
      retries: 10
    networks:
      - internal

  monitor:
    build: ./monitor
    depends_on:
      broker:
        condition: service_healthy
    environment:
      - SPRING_RABBITMQ_HOST=broker
    networks:
      - internal

  gateway:
    build: ./gateway
    ports:
      - "${GATEWAY_PORT:-8083}:80"
    networks:
      - internal
      - default

networks:
  default:
  internal:
    internal: true