[package]
name = "service1"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = "0.11.20"
chrono = "0.4.30"
futures-lite = "2.0.1"
lapin = "2.3.1"
async-trait = "0.1.73"
uuid = { version = "1.6.1", features = ["v4"] }
log = "0.4.20"
