[package]
name = "service1"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = "0.11.20"
chrono = "0.4.30"
amqprs = "1.4.1"
async-trait = "0.1.73"
